### ISSUE TITLE
本地测试更改API url 验证码无法修改

### ISSUE THREAD

**Issue by jinfagang** [mlogclub/bbs-go#83]
![image](https://user-images.githubusercontent.com/21303438/95830344-1b42f700-0d6a-11eb-903e-250827923967.png)

验证码无法加载

**Comment by hp-caoy** [comment]
同问， 登录和注册的验证码都加载不出来

**Comment by hp-caoy** [comment]
可能原因在这里 #81

**Comment by feitian124** [comment]
找来半天找到原因了:

如果不在 docker 里面跑， 前后端分开运行，则开发时应该将 BaseUrl 改为前端访问地址(带端口)，如 http://127.0.0.1:3000

```yml
Env: dev # 环境，线上环境：prod、测试环境：dev
BaseUrl: http://127.0.0.1:3000 # 网站域名，开发时应该使用前端访问地址(带端口)，如 http://127.0.0.1:3000
Port: 8082 # 端口
```
